---
- name: Install certificates bundle
  package:
    name: ca-certificates
    state: present

- name: Enable apt downloads over https
  package:
    name: apt-transport-https
    state: present

- name: Add InfluxDB repository key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key

- name: Add InfluxDB repository
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install InfluxDB
  package:
    name: influxdb
    state: present
  notify: Start InfluxDB
