---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ubuntu_trusty
    alias: 'ubuntu:14.04'
  - name: ubuntu_xenial
    alias: 'ubuntu:16.04'
  - name: ubuntu_bionic
    alias: 'ubuntu:18.04'
  - name: ubuntu_cosmic
    alias: 'ubuntu:18.10'
  - name: debian_jessie
    alias: 'images:debian/8'
  - name: debian_stretch
    alias: 'images:debian/9'

provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
